coverage:
  precision: 2
  round: down
  range: "50...100"

  status:
    project:
      default:
        # basic
        threshold: 2.0%
    patch: no
    changes: no

comment:
  layout: "header, sunburst, diff, files"

